project:
  type: website
  output-dir: docs

website:
  title: "Calidad del agua en El Confital"
  page-footer:
    left: |
      Página web por <a href="https://orcid.org/0009-0005-4889-3412">Vera Gómez-Limón Gallardo</a>.
    center:
      - text: Código fuente
        href: https://codeberg.org/veraglg/bahiaconfital
    right: |
      Este sitio ha sido hecho con <a href="https://quarto.org/">Quarto</a>.

  navbar:
    left:
      - text: "La duda"
        href: index.qmd
      - sidebar:resultados
      - about.qmd
  
  sidebar:
    - id: resultados
      title: "Resultados"
      contents: 
        - indicadores.qmd
        - citometria.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    lang: es

execute: 
  echo: false
  freeze: auto

bibliography: _references.bib
csl: apa-numeric-superscript.csl

