project:
  type: website
  output-dir: docs

website:
  title: "Calidad del agua en El Confital"
  favicon: patron.png
  site-url: https://veraglg.github.io/bahiaconfital/
  page-footer:
    left: |
      Página web por <a href="https://orcid.org/0009-0005-4889-3412">Vera Gómez-Limón Gallardo</a>.
    center: |
      <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a><img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/nc.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/sa.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;">
    right: |
      Este sitio ha sido hecho con <a href="https://quarto.org/">Quarto</a>.

  navbar:
    left:
      - text: "La duda"
        href: index.qmd
      - sidebar:resultados
      - about.qmd
    right:
      - text: '![](orcid.svg "ORCiD de la autora"){height=1.2em}'
        href: https://orcid.org/0009-0005-4889-3412
      - text: '![](codeberg.svg "Codigo fuente"){height=1.2em}'
        href: https://codeberg.org/veraglg/bahiaconfital
  
  sidebar:
    - id: resultados
      title: "Resultados"
      contents: 
        - indicadores.qmd
        - citometria.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    lang: es

execute: 
  echo: false
  freeze: auto

bibliography: _references.bib
csl: apa-numeric-superscript.csl

