---
title: Materiales y métodos de secuenciación
author:
  name: Markel Gómez Letona
  orcid: 0000-0001-9325-3979
  affiliation: Instituto de Investigacións Mariñas (IIM-CSIC)
---

::: {.callout-caution}
## Sección cientifico-técnica

Esta sección contiene especificaciones científico-técnicas para una mejor reproducibilidad de los resultados. Puedes saltarte esta sección si no estás familiarizada con las metodologías de secuenciación de material genético.
:::

::: {.callout-note}
Traducción realizada con la versión gratuita del traductor [DeepL.com](https://deepl.com)
:::

## Extracción

La extracción de ADN se llevó a cabo siguiendo el protocolo de fenol-cloroformo. Se añadió 1 ml de tampón de lisis (50 ml de Tris-HCl 1 M, pH 8,3; 80 ml de EDTA 0,5 M, pH 8,0; 265 g de [sacarosa](https://www.sigmaaldrich.com/catalog/product/sigma/84097?lang=es&region=ES) (Sigma-Aldrich); 870 ml de agua ultrapura) a los tubos de microcentrífuga que contenían los filtros de muestra, junto con 25 µl de [lisozima](https://www.sigmaaldrich.com/catalog/product/sigma/l6876?lang=es&region=ES) recién preparada (1 mg de lisozima en 25 µl de tampón de lisis, concentración final 1 mg/ml; Sigma-Aldrich). La mezcla se incubó a 37 °C durante 45 minutos con agitación suave. Posteriormente se añadieron 25 µl de [proteinasa K](https://www.sigmaaldrich.com/catalog/product/mm/124568?lang=es&region=ES) recién preparada (0,2 mg de proteinasa K en 25 µl de tampón de lisis, concentración final: 0,2 mg/ml; Sigma-Aldrich) y 100 µl de [SDS](http://www.thermofisher.com/order/catalog/product/AM9820) al 10 % (Thermo Fisher), incubando la mezcla a 55 °C durante 1 hora con agitación suave. A continuación, se añadieron 0,75 ml de mezcla de [fenol:CHCl₃:IAA](https://www.thermofisher.com/order/catalog/product/AM9730#/AM9730) (25:24:1; Thermo Fisher), se agitó ligeramente con vórtex y se centrifugó durante 10 minutos a 14 000 rpm. La fase acuosa resultante se transfirió a un nuevo tubo y se repitió el paso: se añadieron 0,75 ml de mezcla de [CHCl₃:IAA](https://www.sigmaaldrich.com/catalog/product/sigma/c0549?lang=es&region=ES), se agitó ligeramente con el vórtex y se centrifugó durante 10 minutos a 14.000 rpm. El tercer y último paso de la extracción se llevó a cabo añadiendo 0,75 ml de mezcla de CHCl₃:IAA (24:1, Sigma-Aldrich), agitando ligeramente con vórtex y centrifugando durante 10 minutos a 14.000 rpm. La fase acuosa resultante se transfirió a un nuevo tubo para proceder a la precipitación del ADN. La precipitación del ADN se realizó siguiendo a Green y Sambrook[@green2017], incluyendo glicógeno según Zou et al.[@zou2021]. Se añadieron 0,1 volúmenes de [acetato de sodio](https://www.thermofisher.com/order/catalog/product/AM9740#/AM9740) (3M, pH 5,5; Thermo Fisher), 0,02 volúmenes de [glicógeno](https://www.thermofisher.com/order/catalog/product/AM9510?SID=srch-srp-AM9510#/AM9510?SID=srch-srp-AM9510) (5 mg/mL; Thermo Fisher) y 0,65 volúmenes de [isopropanol](https://www.sigmaaldrich.com/catalog/product/sigma/i9516?lang=es&region=ES) (Sigma-Aldrich), y se centrifugó durante 40 minutos a 4 °C y 14.000 rpm. El líquido sobrenadante resultante se retiró con cuidado. El sedimento de ADN se lavó con 650 µl de etanol helado (70 %) y se centrifugó durante 30 minutos a 4 °C y 14.000 rpm. El sobrenadante resultante se retiró de nuevo con cuidado y se dejó el tubo abierto para permitir que el sedimento de ADN se secara. Por último, los sedimentos se disolvieron en 50 µl de TRIS (10 mM).

## Secuenciación

La preparación de la biblioteca y la secuenciación del ADN extraído se llevaron a cabo en AllGenetics & Biology SL (A Coruña, España; allgenetics.eu) en dos ciclos de secuenciación independientes. La región V4-V5 del gen 16S rRNA se amplificó utilizando los cebadores universales 515F-Y (5’ GTGYCAGCMGCCGCGGTAA 3’)[@parada2016] y 926R (5’ CCGYCAATTYMTTTRAGTTT 3’)[@quince2011] y se secuenció en una fracción de una célula de flujo Illumina NovaSeq PE250 (lecturas de extremos emparejados, 2 × 250 pb).

Descripción detallada proporcionada por AllGenetics:

::: {.blockquote}
Cuantificamos la concentración de ADN en cada extracto utilizando el ensayo Qubit High Sensitivity dsDNA Assay (Thermo Fisher Scientific).

Las identificaciones de las muestras y los valores de cuantificación del ADN se recogen en la Tabla 1.

Teniendo en cuenta esos valores de cuantificación, se seleccionaron un total de 476 muestras para los análisis de metabarcoding de ADN (todas ellas con el marcador 16S y 35 de ellas con el marcador 18S; véase la Tabla 1).

Preparación de la biblioteca de metabarcoding de ADN y secuenciación
Se construyó un tipo de biblioteca diferente para cada taxón de interés con los siguientes pares de cebadores y condiciones:

Para la preparación de la biblioteca bacteriana, se amplificó un fragmento de la región 16S (V4-V5) de unos 415 pb utilizando los siguientes cebadores:

Directo - 515F (5’ GTGYCAGCMGCCGCGGTAA 3’) (Parada et al., 2016)[@parada2016]

Inverso - 926R (5’ CCGYCAATTYMTTTRAGTTT 3’) (Quince et al., 2011)[@quince2011]

Estos cebadores también incluían las secuencias de los cebadores de secuenciación de Illumina unidas a sus extremos 5’.

En la primera etapa de amplificación, se llevaron a cabo las PCR (números 5 a 10, véase la Tabla 1) en un volumen final de 12,5 μL, que contenía 4,5 μL de ADN molde, 0,5 μM de los cebadores, 6,25 μL de Supreme NZYTaq 2x Green Master Mix (NZYTech) y agua ultrapura hasta completar 12,5 μL. La mezcla de reacción se incubó de la siguiente manera: una etapa inicial de desnaturalización a 95 ºC durante 5 min, seguida de 25 ciclos de 95 ºC durante 30 s, 43 ºC durante 45 s, 72 ºC durante 45 s, y una etapa final de extensión a 72 ºC durante 7 min.

Algunas muestras no produjeron una sola banda nítida en el gel de electroforesis de agarosa, por lo que se repitieron diluyendo el ADN (1:10) (PCR número 19, véase la Tabla 1); o añadiendo 3,5 μL de ADN y CES 1X (Ralser et al., 2006) (PCR número 20, véase la Tabla 1).

Para la preparación de la biblioteca de eucariotas, se amplificó un fragmento de la región 18S de unos 415 pb utilizando los siguientes cebadores:

Directo - TAReuk454FWD1 (5’ CCAGCASCYGCGGTAATTCC 3’) (Stoeck et al., 2010)

Inverso - V4RB (5’ TAIACYTCIGGRTGICCRAARAAYCA 3’) (Balzano et al., 2015)

Estos cebadores también incluían las secuencias de cebadores de secuenciación Illumina unidas a sus extremos 5’.

En la primera etapa de amplificación, las PCR se llevaron a cabo en un volumen final de 12,5 μL, que contenía 1,25 μL de ADN molde, 0,5 μM de los cebadores, 3,13 μL de Supreme NZYTaq 2x Green Master Mix (NZYTech) y agua ultrapura hasta completar los 12,5 μL. La mezcla de reacción se incubó de la siguiente manera: una etapa inicial de desnaturalización a 95 ºC durante 5 min, seguida de 35 ciclos de 95 ºC durante 30 s, 42 ºC durante 45 s, 72 ºC durante 45 s, y una etapa final de extensión a 72 ºC durante 7 min.

Los marcadores de oligonucleótidos necesarios para multiplexar diferentes bibliotecas en el mismo pool de secuenciación se incorporaron en una segunda etapa de amplificación en condiciones idénticas, pero con solo 5 ciclos y una temperatura de hibridación de 60 ºC. Para obtener una visión general esquemática del proceso de preparación de bibliotecas, véase la figura 1 en Vierna et al. (2017).

Se incluyó un control negativo que no contenía ADN (BPCR) en cada ronda de PCR para comprobar si había contaminación durante la preparación de las bibliotecas.

Verificamos el tamaño de las bibliotecas sometiéndolas a geles de agarosa al 2 % teñidos con GreenSafe (NZYTech) y fotografiándolas bajo luz UV. A continuación, purificamos las bibliotecas utilizando las perlas magnéticas Mag-Bind RXNPure Plus (Omega Bio-tek), siguiendo las instrucciones del fabricante.

Las bibliotecas terminadas se agruparon en cantidades equimolares según los resultados de una cuantificación con el ensayo Qubit dsDNA HS (Thermo Fisher Scientific).

La mezcla se secuenció en una fracción de una célula de flujo NovaSeq PE250 (Illumina), con el objetivo de obtener un rendimiento total de 20 gigabases (18 gigabases para 16S y 2 gigabases para 18S).

#### Control de calidad de los datos de secuenciación

Los datos brutos de Illumina de extremos emparejados para cada biblioteca consisten en lecturas directas (R1) e inversas (R2) almacenadas en archivos separados, que también incluyen las puntuaciones de calidad de las lecturas. Eliminamos cualquier rastro potencial de dímeros de adaptador utilizando Cutadapt v3.5[@martin2011].

A continuación, evaluamos la calidad de los archivos FASTQ con el software FastQC (Andrews, 2010)[@andrews2010] y resumimos los resultados utilizando MultiQC (Ewels, 2016)[@ewels2016].
:::

## Procesamiento

Los resultados de la secuenciación se procesaron en la plataforma de bioinformática marina (Marbits, marbits.icm.csic.es) del Institut de Ciències del Mar (ICM-CSIC, Barcelona). Se utilizó Cutadapt[@martin2011] para eliminar los cebadores.

## Archivos

### Tabla 16S

`canteras_microbiome\dada2_canteras_16s\data\dada2\04_decontam-and-filter\canteras\canteras_seqtab_decontam_filter.rds`

### Tabla 16S taxonomía

`canteras_microbiome\dada2_canteras_16s\data\dada2\04_decontam-and-filter\canteras\canteras_tax_assignation_decontam_filter.rds`

### Secuencias 16S

`canteras_microbiome\dada2_canteras_16s\data\dada2\04_decontam-and-filter\canteras\canteras_sequences_decontam_filter.rds`

### Tabla 18S

`canteras_microbiome\dada2_canteras_18s\data\dada2\04_decontam-and-filter\canteras\canteras_seqtab_decontam_filter.rds`

### Tabla 18S taxonomía

`canteras_microbiome\dada2_canteras_18s\data\dada2\04_decontam-and-filter\canteras\canteras_tax_assignation_decontam_filter.rds`

### Secuencias 18S

`canteras_microbiome\dada2_canteras_18s\data\dada2\04_decontam-and-filter\canteras\canteras_sequences_decontam_filter.rds`